name: sort_game
description: "排序物語 - 一個有趣的液體排序益智遊戲"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  vibration: ^1.8.4
  confetti: ^0.7.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background/