name: aetherys
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.2
  uuid: ^4.5.1
  fl_chart: ^0.70.2 # Downgraded from 0.62.0 to a more stable version
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true