class GetSustainableVolumePool {
  final String itemId;
  final String name;
  final String type;
  final int coinAmount;
  final String price;
  final String description;
  final String locale;
  final String category;

  const GetSustainableVolumePool({
    required this.itemId,
    required this.name,
    required this.type,
    required this.coinAmount,
    required this.price,
    required this.description,
    required this.locale,
    required this.category,
  });
}

const List<GetSustainableVolumePool> shopInventory = <GetSustainableVolumePool>[
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.099',
    name: '60 Spirit Gems',
    type: 'consumable',
    coinAmount: 60,
    price: '0.99',
    description: 'Purchasing 60 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.199',
    name: 'Value Pack 2',
    type: 'consumable',
    coinAmount: 120,
    price: '1.99',
    description: 'Purchasing Value Pack 2',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.299',
    name: 'Value Pack 3',
    type: 'consumable',
    coinAmount: 180,
    price: '2.99',
    description: 'Purchasing Value Pack 3',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.399',
    name: 'Value Pack 4',
    type: 'consumable',
    coinAmount: 240,
    price: '3.99',
    description: 'Purchasing Value Pack 4',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.499',
    name: '300 Spirit Gems',
    type: 'consumable',
    coinAmount: 300,
    price: '4.99',
    description: 'Purchasing 300 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.599',
    name: 'Value Pack 6',
    type: 'consumable',
    coinAmount: 360,
    price: '5.99',
    description: 'Purchasing Value Pack 6',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.799',
    name: 'Value Pack 7',
    type: 'consumable',
    coinAmount: 480,
    price: '7.99',
    description: 'Purchasing Value Pack 7',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.899',
    name: 'Value Pack 8',
    type: 'consumable',
    coinAmount: 540,
    price: '8.99',
    description: 'Purchasing Value Pack 8',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.999',
    name: '680 Spirit Gems',
    type: 'consumable',
    coinAmount: 680,
    price: '9.99',
    description: 'Purchasing 680 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.1499',
    name: '980 Spirit Gems',
    type: 'consumable',
    coinAmount: 980,
    price: '14.99',
    description: 'Purchasing 980 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.1999',
    name: '1280 Spirit Gems',
    type: 'consumable',
    coinAmount: 1280,
    price: '19.99',
    description: 'Purchasing 1280 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.2999',
    name: '1980 Spirit Gems',
    type: 'consumable',
    coinAmount: 1980,
    price: '29.99',
    description: 'Purchasing 1980 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.4699',
    name: 'Value Pack 14',
    type: 'consumable',
    coinAmount: 2800,
    price: '46.99',
    description: 'Purchasing Value Pack 14',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.4999',
    name: '3280 Spirit Gems',
    type: 'consumable',
    coinAmount: 3280,
    price: '49.99',
    description: 'Purchasing 3280 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
  GetSustainableVolumePool(
    itemId: 'com.htqoeqk.9999',
    name: '6480 Spirit Gems',
    type: 'consumable',
    coinAmount: 6480,
    price: '99.99',
    description: 'Purchasing 6480 Spirit Gems',
    locale: 'en_US',
    category: 'basic',
  ),
];
