import 'package:flutter/material.dart';

class Character {
  final String name;
  final int attackPower;
  final int mana;
  final String description;
  final String imagePath;
  final int level;

  const Character({
    required this.name,
    required this.attackPower,
    required this.mana,
    required this.description,
    required this.imagePath,
    required this.level,
  });
}

// 角色列表
const List<Character> characters = [
  Character(
    name: '青云子',
    attackPower: 100,
    mana: 80,
    description: '齐天大圣，拥有强大的战斗力和法力。优点是高攻击和灵活性，缺点是防御较低，操作性较强，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_1.png',
    level: 5,
  ),
  Character(
    name: '白龙王',
    attackPower: 70,
    mana: 50,
    description: '憨态可掬，擅长使用九齿钉耙。优点是高生命值和防御，缺点是攻击力较低，操作性较简单，适合承受伤害。',
    imagePath: 'assets/xyjs_2.png',
    level: 3,
  ),
  Character(
    name: '紫霞仙子',
    attackPower: 80,
    mana: 60,
    description: '忠诚可靠，擅长防御和支援。优点是均衡的属性和良好的支援能力，缺点是缺乏爆发力，操作性适中，适合团队作战。',
    imagePath: 'assets/xyjs_3.png',
    level: 4,
  ),
  Character(
    name: '月白仙子',
    attackPower: 30,
    mana: 100,
    description: '慈悲为怀，擅长法术和治愈。优点是强大的法术和治疗能力，缺点是脆弱，操作性较高，适合后排支援。',
    imagePath: 'assets/xyjs_4.png',
    level: 2,
  ),
  Character(
    name: '风灵子',
    attackPower: 50,
    mana: 40,
    description: '忠诚的坐骑，能帮助团队快速移动。优点是高机动性，缺点是攻击力较低，操作性简单，适合快速支援。',
    imagePath: 'assets/xyjs_5.png',
    level: 1,
  ),
  Character(
    name: '观音菩萨',
    attackPower: 90,
    mana: 120,
    description: '慈悲为怀，能施展强大的法术。优点是高法术输出和治疗能力，缺点是防御较低，操作性较高，适合多种战斗场景。',
    imagePath: 'assets/xyjs_6.png',
    level: 5,
  ),
  Character(
    name: '牛魔王',
    attackPower: 110,
    mana: 70,
    description: '强大的敌人，拥有极高的攻击力。优点是高爆发和强大的控制能力，缺点是法力不足，操作性较高，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_7.png',
    level: 6,
  ),
  Character(
    name: '铁扇公主',
    attackPower: 60,
    mana: 90,
    description: '聪明机智，擅长使用扇子进行攻击。优点是灵活性和控制能力，缺点是输出较低，操作性适中，适合灵活应对战斗。',
    imagePath: 'assets/xyjs_8.png',
    level: 4,
  ),
  Character(
    name: '红孩儿',
    attackPower: 75,
    mana: 65,
    description: '调皮捣蛋，拥有火焰攻击能力。优点是高爆发和灵活性，缺点是防御较低，操作性较高，适合快速打击敌人。',
    imagePath: 'assets/xyjs_9.png',
    level: 3,
  ),
  Character(
    name: '玉兔精',
    attackPower: 55,
    mana: 85,
    description: '灵巧可爱，擅长使用月光法术。优点是高法术输出和机动性，缺点是生命值较低，操作性较高，适合快速支援和输出。',
    imagePath: 'assets/xyjs_10.png',
    level: 2,
  ),
  Character(
    name: '白骨精',
    attackPower: 85,
    mana: 90,
    description: '狡猾的妖怪，擅长使用幻术。优点是高法术输出和灵活性，缺点是防御较低，适合快速打击敌人。',
    imagePath: 'assets/xyjs_11.png',
    level: 4,
  ),
  Character(
    name: '金角大王',
    attackPower: 95,
    mana: 80,
    description: '强大的敌人，拥有强大的攻击力和法力。优点是高爆发，缺点是操作性较高，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_12.png',
    level: 5,
  ),
  Character(
    name: '银角大王',
    attackPower: 90,
    mana: 75,
    description: '金角大王的兄弟，擅长使用法术。优点是高法术输出，缺点是生命值较低，适合后排支援。',
    imagePath: 'assets/xyjs_13.png',
    level: 5,
  ),
  Character(
    name: '小白龙',
    attackPower: 70,
    mana: 100,
    description: '忠诚的伙伴，擅长水系法术。优点是高法术输出和机动性，缺点是攻击力较低，适合支援。',
    imagePath: 'assets/xyjs_14.png',
    level: 3,
  ),
  Character(
    name: '红孩儿',
    attackPower: 75,
    mana: 65,
    description: '调皮捣蛋，拥有火焰攻击能力。优点是高爆发和灵活性，缺点是防御较低，操作性较高，适合快速打击敌人。',
    imagePath: 'assets/xyjs_15.png',
    level: 3,
  ),
  Character(
    name: '白衣女鬼',
    attackPower: 60,
    mana: 85,
    description: '神秘的存在，擅长使用黑暗法术。优点是高法术输出，缺点是生命值较低，适合快速支援和输出。',
    imagePath: 'assets/xyjs_16.png',
    level: 2,
  ),
  Character(
    name: '青龙',
    attackPower: 100,
    mana: 120,
    description: '强大的神兽，拥有极高的攻击力和法力。优点是高爆发和强大的控制能力，适合多种战斗场景。',
    imagePath: 'assets/xyjs_17.png',
    level: 6,
  ),
  Character(
    name: '白虎',
    attackPower: 95,
    mana: 70,
    description: '强大的神兽，擅长物理攻击。优点是高攻击和防御，缺点是法力不足，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_18.png',
    level: 6,
  ),
  Character(
    name: '朱雀',
    attackPower: 85,
    mana: 100,
    description: '神秘的鸟类，擅长火系法术。优点是高法术输出和机动性，缺点是生命值较低，适合快速支援。',
    imagePath: 'assets/xyjs_19.png',
    level: 4,
  ),
  Character(
    name: '玄武',
    attackPower: 80,
    mana: 90,
    description: '强大的神兽，擅长防御和支援。优点是均衡的属性和良好的支援能力，缺点是缺乏爆发力，适合团队作战。',
    imagePath: 'assets/xyjs_20.png',
    level: 4,
  ),
  Character(
    name: '火焰精灵',
    attackPower: 80,
    mana: 100,
    description: '掌控火焰的精灵，擅长范围攻击。优点是高法术输出，缺点是防御较低，适合快速清场。',
    imagePath: 'assets/xyjs_21.png',
    level: 4,
  ),
  Character(
    name: '冰霜巨人',
    attackPower: 120,
    mana: 50,
    description: '强大的冰霜巨人，擅长控制敌人。优点是高生命值和控制能力，缺点是移动缓慢，适合前排抗击。',
    imagePath: 'assets/xyjs_22.png',
    level: 6,
  ),
  Character(
    name: '雷电骑士',
    attackPower: 90,
    mana: 80,
    description: '骑乘雷电的战士，擅长快速打击。优点是高爆发和机动性，缺点是法力消耗大，适合快速击杀。',
    imagePath: 'assets/xyjs_23.png',
    level: 5,
  ),
  Character(
    name: '暗影刺客',
    attackPower: 95,
    mana: 60,
    description: '隐匿于黑暗中的刺客，擅长单体击杀。优点是高爆发和隐蔽性，缺点是脆弱，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_24.png',
    level: 5,
  ),
  Character(
    name: '光明法师',
    attackPower: 70,
    mana: 120,
    description: '掌控光明的法师，擅长治疗和支援。优点是强大的治疗能力，缺点是攻击力较低，适合团队支援。',
    imagePath: 'assets/xyjs_25.png',
    level: 4,
  ),
  Character(
    name: '大地守护者',
    attackPower: 110,
    mana: 40,
    description: '大地的守护者，擅长防御和反击。优点是高防御和生命值，缺点是法力不足，适合持久战。',
    imagePath: 'assets/xyjs_26.png',
    level: 6,
  ),
  Character(
    name: '风之游侠',
    attackPower: 85,
    mana: 70,
    description: '灵活的游侠，擅长远程攻击。优点是高机动性和输出，缺点是防御较低，适合快速打击。',
    imagePath: 'assets/xyjs_27.png',
    level: 4,
  ),
  Character(
    name: '水元素',
    attackPower: 75,
    mana: 90,
    description: '水的化身，擅长控制和支援。优点是高法术输出和控制能力，缺点是生命值较低，适合团队作战。',
    imagePath: 'assets/xyjs_28.png',
    level: 3,
  ),
  Character(
    name: '岩石巨兽',
    attackPower: 130,
    mana: 30,
    description: '强大的岩石巨兽，擅长物理攻击。优点是高生命值和攻击力，缺点是法力不足，适合前排抗击。',
    imagePath: 'assets/xyjs_29.png',
    level: 6,
  ),
  Character(
    name: '梦幻精灵',
    attackPower: 60,
    mana: 110,
    description: '神秘的梦幻精灵，擅长幻术和迷惑。优点是高法术输出和灵活性，缺点是防御较低，适合快速支援。',
    imagePath: 'assets/xyjs_30.png',
    level: 4,
  ),
  Character(
    name: '风暴女巫',
    attackPower: 85,
    mana: 110,
    description: '掌控风暴的女巫，擅长范围控制和输出。优点是高法术输出，缺点是防御较低，适合快速清场。',
    imagePath: 'assets/xyjs_31.png',
    level: 5,
  ),
  Character(
    name: '黑暗骑士',
    attackPower: 100,
    mana: 60,
    description: '隐秘的黑暗骑士，擅长单体击杀和控制。优点是高爆发，缺点是法力消耗大，适合快速击杀敌人。',
    imagePath: 'assets/xyjs_32.png',
    level: 6,
  ),
  Character(
    name: '光辉天使',
    attackPower: 70,
    mana: 120,
    description: '光辉的天使，擅长治疗和支援。优点是强大的治疗能力，缺点是攻击力较低，适合团队支援。',
    imagePath: 'assets/xyjs_33.png',
    level: 4,
  ),
  Character(
    name: '巨石守卫',
    attackPower: 130,
    mana: 40,
    description: '坚固的巨石守卫，擅长防御和反击。优点是高防御和生命值，缺点是法力不足，适合持久战。',
    imagePath: 'assets/xyjs_34.png',
    level: 6,
  ),
];
